### ISSUE TITLE
Rust Subproblem 6

### ISSUE THREAD

**Issue by joyal-mathew** [rpiRobotics/linear-subproblem-solutions#18]

**Comment by joyal-mathew** [comment]
I'm having some trouble with this one because nalgebra (the rust linear algebra library) doesn't provide a function to find the null space of a matrix. I tried using singular value decomposition because it is the method that MATLAB uses under the hood but the nalgebra implementation seems to exclude the null space from the right singular vectors.

With
```
a =

   -0.6039    0.1762   -0.0304   -0.0439
   -0.4880   -0.2362   -0.4965    0.2131
```

In MATLAB:
```
>> [u, s, v]=svd(a);
>> v
v =

   -0.8519    0.4595   -0.2488    0.0341
   -0.1052   -0.6009   -0.6985    0.3742
   -0.4839   -0.5588    0.6494    0.1788
    0.1703    0.3399    0.1691    0.9093
```

Rust gives a v of:
```
  ┌                                                                                     ┐
  │  -0.8519348970780302 -0.10518410494570324 -0.48386706291609144   0.1703405431257414 │
  │  -0.4595201363836715   0.6008854152768923   0.5587845889092609  -0.3399084364398107 │
  └                                                                                     ┘
```

**Comment by aelias36** [comment]
One solution is to compute the eigenvectors of $A^\top A$ with eigenvalue 0. This is the same as calculating the SVD (except the singular values are squared.)  I'm not sure how computationally efficient this is, though.

https://docs.rs/nalgebra/latest/nalgebra/linalg/struct.SymmetricEigen.html#method.new

Another (faster?) option is to perform QR decomposition on $A^\top$, and then use the last two columns of $Q$. In MATLAB:

```Matlab
[Q, R] = qr(A')
A*Q

ans =

    0.5742   -0.0000    0.0000   -0.0000
    0.2659    1.4771   -0.0000         0
```
https://docs.rs/nalgebra/latest/nalgebra/linalg/struct.QR.html
