### ISSUE TITLE
Directly include files from `general-robotics-toolbox` in this repo

### ISSUE THREAD

**Issue by Link2Link** [rpiRobotics/linear-subproblem-solutions#23]
The "rot.m" is not included.

**Comment by Link2Link** [comment]
function R = rot(k,theta)
k_hat = [0, -k(3), k(2); k(3), 0, -k(1); -k(2), k(1), 0];
R = expm(k_hat*theta);
end

**Comment by aelias36** [comment]
Thanks for bringing this up!

Please notice in the MATLAB readme that one of the dependencies is general-robotics-toolbox, which has an implementation for `rot()`.
https://github.com/rpiRobotics/linear-subproblem-solutions/tree/main/matlab

To make things simpler, I will copy over the specific files from the linear-subproblem-solutions repo into this repo.

**Comment by aelias36** [comment]
Closed with 7a62354fb5e4255dc90571b5f20c3179a1b10675
